Kayttöönotto-ohjeet
hytuslain/hytuslain pull request #35
Opened 2021-10-28 13:31 UTC by tuomoart

Käyttöönotto-ohje jossa on lähinne selitetty auki Slack API -sivuilla tapahtuvat asiat, lokaali ohjelman suorittaminen riippuu kunkin yksilöllisistä tarpeista joten sitä varten on vain ilmoitettu konfigurointiin tarvittavat ympäristömuuttujat. Käsittääkseni tuossa on kaikki mitä ympäristömuuttujat mitä ohjelma tarvitsee.

closes #10

2021-10-30 11:10 UTC, LindaJT submitted a review, later dismissed
Oikein hyvä!

2021-10-31 10:15 UTC, meklu commented on README.md
> +[Botin käyttöönotto-ohje](https://github.com/hytuslain/hytuslain/blob/kayttohjeet/kayttoonottoohjeet.md)
`blob/kayttohjeet` -> `blob/master`

2021-10-31 10:15 UTC, meklu requested changes
Ihan järkevältä näyttää näin pääosin.

2021-10-31 11:43 UTC, meklu approved these changes

2021-10-31 11:44 UTC, merged