Change scheduled message's schedule and content.
hytuslain/hytuslain pull request #37
Opened 2021-10-29 12:23 UTC by pinjaw

This branch overwrites the previous scheduled message with the following changes:
- The message is sent every weekday, for now at 7 AM.
- The message lists all the people who have signed up to office for that day.
The message is sent to all of the public channels the bot is a member of, as before.
Closes #33

2021-10-30 11:05 UTC, LindaJT reviewed
Näyttää minusta toimivalta. :)

2021-10-30 11:06 UTC, LindaJT submitted a review, later dismissed

2021-11-03 07:09 UTC, meklu requested changes
Näyttää ihan järkevältä.

2021-11-03 11:56 UTC, meklu approved these changes

2021-11-04 08:11 UTC, LindaJT submitted a review, later dismissed

2021-11-04 16:32 UTC, merged