Robot e2e
hytuslain/hytuslain pull request #47
Opened 2021-11-13 11:42 UTC by LindaJT

E2e-testauksen aloittaminen Robot Frameworkilla. Testikäyttäjien sähköpostit on edelleen mukana variables.robot-tiedostossa testauksen helpottamiseksi. Kaikki testitapaukset saa ajettua e2e-kansiossa komennolla `robot --outputdir results -v USER_PASSWORD:salasana -v GUEST_PASSWORD:salasana testcases` .

2021-11-17 11:11 UTC, kukaan commented
Testien ajaminen vaatii pynput, python-decouple, robotframework ja robotframework-selenium2library Python-kirjastojen asentamisen. Lisäksi täytyy lisätä .env-tiedostoon seuraava rivi: `COMMAND_PREFIX=testi`.

2021-11-17 14:06 UTC, meklu commented
Pari huomiota.
- Hakemiston `test/e2e/results/` pitäisi vissiinkin olla listattuna `.gitignore`-tiedostossa. Generoitu raportti ei kuulune repositorioon.
- Onko tuo sanakirja `test/e2e/en-GB-9-0.bdic` välttämätön testien toiminnan kannalta? Hieman arveluttaa puolen megan binääritiedoston sisällyttäminen tähän repoon.

2021-11-17 14:13 UTC, meklu commented
> Testien ajaminen vaatii pynput, python-decouple, robotframework ja robotframework-selenium2library Python-kirjastojen asentamisen.

Pythonista paljoa tietämättä, olisiko nämä mahdollista määritellä jossain PIPin konffitiedostossa (jos PIPillä on jokin `package.json`-filua vastaava menetelmä)?

> Lisäksi täytyy lisätä .env-tiedostoon seuraava rivi: `COMMAND_PREFIX=testi`.

Kokeilematta uskoisin, että testien ajamiseen riittäisi määritellä ympäristömuuttujan arvo ihan komentorivilläkin, mallia

    COMMAND_PREFIX=testi <testikomento tähän>

2021-11-17 15:04 UTC, LindaJT commented
> * Hakemiston `test/e2e/results/` pitäisi vissiinkin olla listattuna `.gitignore`-tiedostossa. Generoitu raportti ei kuulune repositorioon.

Mun käsityksen mukaan tuo raportti-kansio on yleensä mukana repositoriossa ja workflowssa sitten paketoidaan jokaisen ajon jälkeen raportit zip-paketiksi ja viedään sinne raportti-kansioon. Tän voi varmasti tehdä jotenkin toisellakin tapaa, mutta näin oon itse ymmärtänyt. Tässä yksi esimerkki mitä olen katsonut: [linkki](https://github.com/laojala/robot_docker_demo/blob/master/.github/workflows/run_robot_framework_tests.yml)

> * Onko tuo sanakirja `test/e2e/en-GB-9-0.bdic` välttämätön testien toiminnan kannalta? Hieman arveluttaa puolen megan binääritiedoston sisällyttäminen tähän repoon.

Ei varmasti ole, en itseasiassa tiedä miksi se on tuon tuonne tuupannut. Poistan sen.

> * Entä pitäisikö polun `test/e2e/resources/__pycache__/` olla myös ignoroitu? Sieltä löytyy nyt myös jollain tapaa käännetty Python-pätkän binääri.

Tässä sama homma kuin edellisessä. Ignoroin sen.

2021-11-17 15:08 UTC, LindaJT commented
> > Testien ajaminen vaatii pynput, python-decouple, robotframework ja robotframework-selenium2library Python-kirjastojen asentamisen.
> 
> Pythonista paljoa tietämättä, olisiko nämä mahdollista määritellä jossain PIPin konffitiedostossa (jos PIPillä on jokin `package.json`-filua vastaava menetelmä)?

En ole varma, ei ole itsellä tullut vastaan, mutta selvittelen. Workflowssa nuo testit olisi tarkoitus ajaa Robot framework docker-kontissa, missä ainakin nuo robot framework ja selenium-kirjastot on mukana.

> > Lisäksi täytyy lisätä .env-tiedostoon seuraava rivi: `COMMAND_PREFIX=testi`.
> 
> Kokeilematta uskoisin, että testien ajamiseen voisi riittää määritellä ympäristömuuttujan arvo ihan komentorivilläkin, mallia
> 
> ```
> COMMAND_PREFIX=testi <testikomento tähän>
> ```

Joo vaatii pienen muutoksen, mutta tuo olisi varmasti järkevä toteuttaa noin. Järkevämpää workflownkin kannalta.

2021-11-17 15:20 UTC, meklu commented
> > Pythonista paljoa tietämättä, olisiko nämä mahdollista määritellä jossain PIPin konffitiedostossa (jos PIPillä on jokin `package.json`-filua vastaava menetelmä)?
> 
> En ole varma, ei ole itsellä tullut vastaan, mutta selvittelen. Workflowssa nuo testit olisi tarkoitus ajaa Robot framework docker-kontissa, missä ainakin nuo robot framework ja selenium-kirjastot on mukana.

Okei, hyvä. Voitaisiin ottaa käytännöksi ajaa integraatiotestit paikallisestikin kontin avulla.

2021-11-17 17:00 UTC, kukaan requested changes
En saanut tätä toimimaan täysin konsistentisti omalta ilmeisen hitaalta koneelta suoritettuna. Monessa kohdassa heräsi kysymys siitä, voisiko toistoa välttää jotenkin. Lisäksi olisi syytä lisätä results-kansio gitignoreen ja poistaa sen sisältö.

2021-11-21 08:59 UTC, LindaJT commented on test/e2e/resources/HelpFunc.py
> +        command = "/{prefix}listaa".format(prefix=config('COMMAND_PREFIX'))
Poistin tämän funktion kokonaan, koska Melkerin ehdotuksesta lisäsin COMMAND_PREFIXin komentorivimuuttujaksi. Tässä ratkaisussa on etuna myös se, että testit voi helpommin ajaa erillisenä myös jollekin toiselle botille. Nyt testit voi siis ajaa komennolla `robot --outputdir results -v USER_PASSWORD:salasana -v GUEST_PASSWORD:salasana -v COMMAND_PREFIX:testi testcases` . Tämän muutoksen seurauksena ei myöskään enää tarvita python-decouple kirjastoa.

2021-11-21 09:03 UTC, LindaJT commented on test/e2e/resources/variables.robot
> +${USER_EMAIL}    508ef628-b957-4779-98bf-80c0963fb4f2@mailslurp.com
Tarkoitatko näiden lisäämistä .env- tiedostoon vai komennon yhteydessä annettaviksi muuttujiksi? Olen jättänyt ne toistaiseksi tähän, koska testejä tekiessä olisi työlästä antaa nämä kaikki aina parametreinä komennon yhteydessä. Kun testit lisätään ci workflowhun, niin silloin nämä kaikki annetaan Docker kontille parametreinä.

2021-11-21 09:04 UTC, LindaJT commented on test/e2e/resources/variables.robot
> +${GUEST_EMAIL}    batoh25883@fretice.com
Muutettu. Uuden käyttäjän tiedot löytyvät SECRETS-tiedostosta.

2021-11-21 09:08 UTC, LindaJT commented on test/e2e/testcases/01__guest_suite.robot
> +Suite Teardown    common.Close Test Browser
Mielestäni ei. Jokaisen test suiten alussa täytyy kuitenkin kirjautua sisään tietyllä käyttäjäroolilla ja best practises kuuluu, että test suitejen välissä suljetaan selain. Muuten jonkun aikaisemman test suiten feilaaminen voisi vaikuttaa seuraavan suiten toimintaan.

2021-11-21 09:21 UTC, LindaJT commented on test/e2e/testcases/01__guest_suite.robot
> +    Set Global Variable    ${LIST_COMMAND}    ${LIST_COMMAND}
En keksinyt miten saisi määritettyä ennen test caseja, mutta muutin niin, että tuo LIST_COMMAND määritellään vain kerran guest suitessa.

2021-11-21 09:30 UTC, LindaJT commented
> En saanut tätä toimimaan täysin konsistentisti omalta ilmeisen hitaalta koneelta suoritettuna. Monessa kohdassa heräsi kysymys siitä, voisiko toistoa välttää jotenkin. Lisäksi olisi syytä lisätä results-kansio gitignoreen ja poistaa sen sisältö.

Yritin muuttaa testejä niin, että ne toimisivat varmemmin ja niin, että sleeppiä käytetään vain kun odotetaan botin tekevän jotain. Koitatko toimiiko nyt sunkin koneella paremmin? Results-kansion sisältö on nyt ignoroitu.

2021-11-26 21:02 UTC, kukaan approved these changes, later dismissed
erinomaista! testit myös toimivat nyt konsistentisti koneellani. pitikö nuo binääritiedostot vielä poistaa?

2021-12-04 10:50 UTC, meklu commented
> ### Robot Results
> tada Passed 8 / 9 fire Failed 1 / 9
> 
> ### Failed Tests
> Name	Message	Suite
> List Saturday Command Gives Correct Respond	Element '(//div[@Class='c-virtual_list__scroll_container'])[2]/div[@Class='c-virtual_list__item'][last()]' should have contained text 'Kukaan ei ole toimistolla lauantaina 4.12' but its text was 'Only visible to you test-hybridilusmuAPP 10:38 AM Kukaan ei ole toimistolla tänään.'.	Message Tab

Näköjään käyttäytyminen on muuttunut masterissa, ja tämänpäiväisiin testeihin tulee aina merkkijono "tänään" viikonpäivän sijaan. Tämä testi olisi siis toiminut eilen ajettuna :D

2021-12-04 11:05 UTC, meklu approved these changes

2021-12-08 14:45 UTC, kukaan approved these changes

2021-12-08 14:46 UTC, merged